remote_theme: "mmistakes/minimal-mistakes@4.19.1"
repository: "at-ishikawa/at-ishikawa.github.io"
title: at-ishikawa's pages
description: The notes about technical things when at-ishikawa looked into them for future use or faced troubles
plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-gist
#   - jemoji
  - jekyll-feed
  - jekyll-include-cache
minimal_mistakes_skin: air
search: true
search_full_content: true

after_footer_scripts:
  # https://www.osano.com/cookieconsent/download/
  - "https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js"
  - /assets/js/cookie_banner.js
include:
  - docs

author:
  name   : "at-ishikawa"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/at-ishikawa"
    - label: "Medium"
      icon: "fas fa-fw fa-link"
      url: "https://medium.com/@at_ishikawa"

# posts url
permalink: pretty
collections:
  docs:
    output: true

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true

  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      toc: true
      toc_label: "Table of contents"
      sidebar:
        nav: "docs"
      read_time: true
      comments: true
      share: true

analytics:
  provider: "google-universal"
  google:
    tracking_id: "UA-151505454-1"

comments:
  provider: "utterances"
  utterances:
    theme: "github-light"
    issue_term: "pathname"
