version: '3.8'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 33306:3306

volumes:
  data:
    driver: local
