FROM mysql/mysql-server:8.0

# RUN apt-get update && apt-get install -y tar gzip wget
# RUN wget 'https://github.com/github/gh-ost/releases/download/v1.1.2/gh-ost-binary-linux-20210617134741.tar.gz' \
#     && tar -xzvf gh-ost-binary-linux-20210617134741.tar.gz \
#     && mv gh-ost /usr/local/bin/
